services:
  - type: web
    name: cogniflow-erp
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_vgI4Pf9hUuaN@ep-fragrant-sky-a436xyqj-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SESSION_SECRET
        generateValue: true