services:
  - type: web
    name: cogniflow-erp
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cogniflow-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: cogniflow-db
    plan: free
    databaseName: cogniflow_erp
    user: cogniflow_user